@startuml login
skinparam style strictuml
skinparam SequenceMessageAlignment center
patient -> interface_utilisateur :    1 : Demande de la page de connexion
activate interface_utilisateur
interface_utilisateur -->patient:     2 : Affcihcer formulaire de connexion 
deactivate interface_utilisateur
patient ->> interface_utilisateur :   3 : Saidir le nom d'utilisateur ou le email
patient ->> interface_utilisateur :   4 : Saidir le mot de passe
patient -> interface_utilisateur :    5 : Clique sur le boutton << Se connecter >>
interface_utilisateur -> SGBD :    6  :Verfie si le nom d etulisateur et le mot de passe son correct
activate interface_utilisateur
activate SGBD
deactivate interface_utilisateur
alt Nom d'utilasateur nesxite pas
    SGBD --> interface_utilisateur : 7: Erreur Le nom d'utilisateur incorrect
    interface_utilisateur --> patient : 8: Nom d'utilisateur incorrect 
    activate interface_utilisateur
    deactivate interface_utilisateur
else
    alt Mot de passe incorrect
        SGBD --> interface_utilisateur : 9: Erreur mot de passe incorrect
        deactivate SGBD
        interface_utilisateur --> patient : 10: Mot de pass incorrect
        activate interface_utilisateur
        deactivate interface_utilisateur
    else
        SGBD --> interface_utilisateur: 11 : Connextion avec succè
        interface_utilisateur --> patient: 12 : Afficher le profile de patient
        activate interface_utilisateur
        deactivate interface_utilisateur
    end
end
@enduml